title: Pythonを極めて無双した件
author: 鳳凰院 龍聖
version: "1.0"
logo: cover.png
copyright: "2025, 鳳凰院 龍聖"

only_build_toc_files: true

execute:
  timeout: 1000
  execute_notebooks: force


launch_buttons:
  notebook_interface: jupyterlab
  colab_url: ""

repository:
  url: https://github.com/matt76k/beginners-py
  path_to_book: _sources
  branch: gh-pages

latex:
  latex_documents:
    targetname: book.tex

html:
  favicon: cover.png
  extra_css: 
    - https://fonts.googleapis.com/css2?family=BIZ+UDGothic

sphinx:
  config:
    nb_execution_mode: auto
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    language: ja
    epub_basename: "BeginnersPy"
    epub_cover: ["cover.png", ""]
    suppress_warnings:
      - "myst.directive_unknown"
      - "epub.unknown_project_files"
    # imgmath_image_format: 'svg'
  extra_extensions:
    - sphinx_proof
    - sphinx_exercise
